version: '3.7'

services:
  web:
    build: data
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data/:/usr/src/data/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=eltesto

volumes:
  postgres_data:
